<% app_host = ENV.fetch("KAMAL_APP_HOST") %>
<% server_ip = ENV.fetch("KAMAL_SERVER_IP") %>

service: transactions

image: transactions

servers:
  web:
    - &server_ip <%= server_ip %>

proxy:
  ssl: true
  host: <%= app_host %>

registry:
  server: localhost:5555

env:
  secret:
    - RAILS_MASTER_KEY
    - ADMIN_EMAIL
    - ADMIN_PASSWORD
    - OPENAI_API_KEY
    - RESEND_API_KEY
    - MAILER_FROM
  clear:
    APP_URL: https://<%= app_host %>
    APP_HOST: <%= app_host %>
    APP_PROTOCOL: https
    RUBYLLM_MODEL: <%= ENV.fetch("RUBYLLM_MODEL", "gpt-5-nano") %>
    SOLID_QUEUE_IN_PUMA: true

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

volumes:
  - "transactions_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64
